version: "3.7"
services:
  # Web service layer & Application service layer
  node:
    build:
      context: backend
    command: nodemon ./src/server.js
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/opt/cric/backend"

  angular:
    build:
      context: frontend
    ports:
      - "8080:80"
    volumes:
      - "./frontend/src/:/usr/share/nginx/html"
