version: "3.7"
services:
  # Web service layer & Application service layer
  node:
    build:
      context: backend
    command: nodemon ./src/server.js
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/opt/cric/backend"
      #  Anonymous volume to avoid overwritten by the mounting of the host directory at runtime.
      - "/opt/cric/backend/node_modules"

  angular:
    build:
      context: frontend
    command: ng serve
    ports:
      - "8080:4200"
    volumes:
      - "./frontend:/opt/cric/frontend"
      #  Anonymous volume to avoid overwritten by the mounting of the host directory at runtime.
      - "/opt/cric/frontend/node_modules"
