apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    name: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      name: angular
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        name: angular
    spec:
      containers:
      # Need to tell the built in development server to bind to the unspecified IP address.
      # In IPv4 that address is 0.0.0.0.
      # Otherwise, you will have "Connection reset by peer".
      # And need to disbale host check otherwise will have "Invalid Host header".
      - args:
        - ng
        - serve
        - --host
        - 0.0.0.0
        - --disable-host-check
        image: cricdatabase/angular:0.1.6-production-all
        imagePullPolicy: ""
        name: angular
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
      restartPolicy: Always
      serviceAccountName: ""
status: {}
