apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    name: angular
  name: angular
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    name: angular
status:
  loadBalancer: {}
