apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cricdatabase
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: database.cric.com.br
    http:
      paths:
      - backend:
          serviceName: angular
          servicePort: 80
  - host: api.database.cric.com.br
    http:
      paths:
      - backend:
          serviceName: nodejs
          servicePort: 3000
