apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cricdatabase
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "cricdatabase.com.br"
    http:
      paths:
      - path: /api
        backend:
          serviceName: nodejs
          servicePort: 3000
      - backend:
          serviceName: angular
          servicePort: 8080
