apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cricdatabase
spec:
  rules:
  - host: database.cric.com.br
    http:
      paths:
      - backend:
          serviceName: angular
          servicePort: 8080
  - host: api.database.cric.com.br
    http:
      paths:
      - backend:
          serviceName: nodejs
          servicePort: 3000
